#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor LVDS1 -d I II III IV V VI
bspc monitor HDMI1 -d I

bspc config border_width         1
bspc config window_gap          4
bspc config top_padding         25

bspc config split_ratio          0.56
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a Aseprite desktop='^5' follow=on
bspc rule -a dolphin desktop='^6' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=on

#Autostart

#if [[ $(xrandr -q | grep -w 'HDMI1 connected')]]; then
#	xrandr --output LVDS1 --primary --mode 1366x768 --rotate normal --output HDMI1 --mode 1920x1080 --rotate normal --right-of LVDS1
#fi


picom &
feh --bg-fill --randomize -D -1200  ~/Pictures/walpapers/* &
$HOME/.config/polybar/launch.sh &
#edex-ui &

