#! /bin/sh

#if [[ $(xrandr -q | grep -w 'HDMI-2 connected')]]; then
#	xrandr --output eDP-1 --primary --mode 1366x768 --rotate normal --output HDMI-2 --mode 1920x1080 --rotate normal --right-of eDP-1
#fi

pgrep -x sxhkd > /dev/null || sxhkd &
nm-applet &
picom --experimental-backends &
feh --bg-fill --randomize -D -1200  ~/Pictures/walpapers/* &
$HOME/.config/polybar/launch.sh &
#edex-ui &






bspc monitor eDP-1 -d I II III IV V VI
bspc monitor HDMI-2 -d I

bspc config border_width         1
bspc config window_gap          4
bspc config top_padding         22

bspc config split_ratio          0.56
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a Aseprite desktop='^5' follow=on
bspc rule -a dolphin desktop='^6' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=on
